/* SUPORT SQL PLUS */

-- LISTA DE TABELAS NO BANCO
 SELECT DISTINCT TABLE_NAME FROM ALL_TABLES WHERE OWNER ='QUALITY' AND TABLE_NAME LIKE 'BLF_%';

 -- LISTA DE PROCEDURES
 SELECT DISTINCT NAME FROM ALL_SOURCE WHERE TYPE = 'PROCEDURE' AND OWNER ='QUALITY';

 -- LISTA DE FUNÇOES
 SELECT DISTINCT NAME FROM ALL_SOURCE WHERE TYPE = 'FUNCTION'  AND OWNER ='QUALITY';

  -- LISTA DE PACKAGE
 SELECT DISTINCT NAME FROM ALL_SOURCE WHERE TYPE = 'PACKAGE'  AND OWNER ='QUALITY';

  -- CONTEUDO DA PROCEDURE
   SELECT TEXT FROM ALL_SOURCE
   WHERE TYPE = 'PROCEDURE'
   AND OWNER ='QUALITY'
   AND NAME='SP_BLF_CLIENTES_LASTINFO';
